version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "web/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: |
            make deps
            apt-get -y -qq update
            apt-get -y -qq install awscli
          working_directory: web

      - save_cache:
          paths:
            - web/node_modules
          key: v1-dependencies-{{ checksum "web/package.json" }}

      - deploy:
          command: make deploy
          working_directory: web
