version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: make deps
          working_directory: ~/fantasyslack/web

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: make deploy
          working_directory: ~/fantasyslack/web
