version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8

    working_directory: ~/fantasyslack/web

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd web && make deps

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd web && make deploy
