# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('python_module_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('channel', models.CharField(max_length=128)),
                ('draft_started_date', models.DateTimeField(null=True)),
                ('draft_ended_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField()),
                ('team_members', models.IntegerField()),
                ('current_state', models.CharField(max_length=32)),
                ('categories', models.ManyToManyField(to='slackbot.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('slack_user_id', models.CharField(max_length=32)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('slack_timestamp', models.CharField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.Category')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SlackBotGameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=64)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.Game')),
            ],
        ),
        migrations.CreateModel(
            name='SlackBotUserDMState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=64)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to='slackbot.Player')),
                ('players', models.ManyToManyField(to='slackbot.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('AD', 'Add'), ('DR', 'Drop'), ('TF', 'Trade For'), ('TT', 'Trade To')], max_length=16)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='managers',
            field=models.ManyToManyField(related_name='games_managed', to='slackbot.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_owned', to='slackbot.Player'),
        ),
        migrations.AddField(
            model_name='draftorder',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.Game'),
        ),
        migrations.AddField(
            model_name='draftorder',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.Team'),
        ),
    ]
