# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackBotUserDMStateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=512)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.SlackBotUserDMState')),
            ],
        ),
        migrations.RenameField(
            model_name='slackbotgamestate',
            old_name='state',
            new_name='state_class',
        ),
    ]
