# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0002_auto_20160502_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackbotuserdmstate',
            old_name='state',
            new_name='state_class',
        ),
    ]
